'use client';

import React, { useState, useEffect, useCallback, useMemo, useRef, Suspense } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import {
  Sparkles,
  CheckCircle2,
  Heart,
  Flame,
  Baby,
  User,
  Calendar,
  MapPin,
  Wallet,
  AlertCircle,
  AlertTriangle,
  Loader2,
  RefreshCw,
  ArrowRight,
  Info,
  Clock,
} from 'lucide-react';
import { AppShell } from '@/components/layout/app-shell';
import { Button } from '@/components/ui/button';
import { AIItineraryResult } from '@/types/database';

interface TemplateOption {
  id: string;
  title: string;
  desc: string;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  prompt: string;
  destination: string;
  days: number;
  budget: number;
}

const TEMPLATES: TemplateOption[] = [
  {
    id: 'solo',
    title: 'Solo Cultural Quest',
    desc: 'Historic sites, local museums, and neighborhood walking exploration',
    icon: User,
    color: 'bg-blue-50 text-blue-600 dark:bg-blue-950/60 dark:text-blue-400',
    prompt: 'Solo 5-day cultural and photography exploration through Kyoto & Osaka',
    destination: 'Kyoto, Japan',
    days: 5,
    budget: 65000,
  },
  {
    id: 'adventure',
    title: 'High-Altitude Adventure',
    desc: 'Mountain hikes, river valley outings, and outdoor day activities',
    icon: Flame,
    color: 'bg-orange-50 text-orange-600 dark:bg-orange-950/60 dark:text-orange-400',
    prompt: '6-day outdoor adventure in Manali & Solang Valley with hiking trails',
    destination: 'Manali, India',
    days: 6,
    budget: 35000,
  },
  {
    id: 'scenic',
    title: 'Scenic Coastal Getaway',
    desc: 'Scenic viewpoints, seaside dinners, and relaxed coastal exploration',
    icon: Heart,
    color: 'bg-rose-50 text-rose-600 dark:bg-rose-950/60 dark:text-rose-400',
    prompt: '7-day scenic getaway along the Amalfi Coast with coastal walking tours',
    destination: 'Amalfi, Italy',
    days: 7,
    budget: 120000,
  },
  {
    id: 'family',
    title: 'Family Exploration',
    desc: 'Kid-friendly parks, beach outings, historic forts, and balanced pacing',
    icon: Baby,
    color: 'bg-teal-50 text-teal-600 dark:bg-teal-950/60 dark:text-teal-400',
    prompt: 'Family-friendly 5-day trip to Goa with beaches and historic landmarks',
    destination: 'Goa, India',
    days: 5,
    budget: 45000,
  },
];

function getTodayString(): string {
  return new Date().toISOString().split('T')[0];
}

function addDaysToDate(dateStr: string, daysToAdd: number): string {
  const d = new Date(dateStr);
  if (isNaN(d.getTime())) return '';
  d.setDate(d.getDate() + daysToAdd);
  return d.toISOString().split('T')[0];
}

interface SavePartialResult {
  tripId: string;
  savedStops: number;
  totalStops: number;
  savedActivities: number;
  totalActivities: number;
  errors: string[];
}

function AITripCreatorContent() {
  const router = useRouter();
  const searchParams = useSearchParams();

  const initialDestination = searchParams.get('destination') || 'Tokyo, Japan';
  const initialPrompt = searchParams.get('prompt') || '';

  // Form State (User-Controlled Inputs)
  const [destination, setDestination] = useState(initialDestination);
  const [title, setTitle] = useState(initialDestination ? `Trip to ${initialDestination}` : '');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [days, setDays] = useState(7);
  const [budget, setBudget] = useState(80000);
  const [prompt, setPrompt] = useState(initialPrompt);

  // Generator & Persistence State
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationError, setGenerationError] = useState<string | null>(null);
  const [validationError, setValidationError] = useState<string | null>(null);
  const [generatedResult, setGeneratedResult] = useState<AIItineraryResult | null>(null);

  // Saving State
  const [isSaving, setIsSaving] = useState(false);
  const [saveStatusText, setSaveStatusText] = useState('');
  const [saveError, setSaveError] = useState<string | null>(null);
  const [partialSaveInfo, setPartialSaveInfo] = useState<SavePartialResult | null>(null);

  const hasAutoGeneratedRef = useRef(false);

  // Handle destination change: also suggest a title if title was default
  const handleDestinationChange = (val: string) => {
    setDestination(val);
    if (!title || title.startsWith('Trip to ') || title === 'My Adventure') {
      setTitle(val ? `Trip to ${val}` : '');
    }
  };

  // Handle days change: sync end date
  const handleDaysChange = (newDays: number) => {
    const clamped = Math.max(1, Math.min(14, newDays));
    setDays(clamped);
    if (startDate) {
      setEndDate(addDaysToDate(startDate, clamped - 1));
    }
  };

  // Handle start date change: sync end date
  const handleStartDateChange = (val: string) => {
    setStartDate(val);
    if (val && days > 0) {
      setEndDate(addDaysToDate(val, days - 1));
    } else if (!val) {
      setEndDate('');
    }
  };

  // Handle end date change: update days count if valid
  const handleEndDateChange = (val: string) => {
    setEndDate(val);
    if (startDate && val) {
      const s = new Date(startDate).getTime();
      const e = new Date(val).getTime();
      if (!isNaN(s) && !isNaN(e) && e >= s) {
        const diffDays = Math.round((e - s) / 86400000) + 1;
        setDays(Math.max(1, Math.min(14, diffDays)));
      }
    }
  };

  const handleSelectTemplate = (tpl: TemplateOption) => {
    setDestination(tpl.destination);
    setTitle(`Trip to ${tpl.destination}`);
    setDays(tpl.days);
    setBudget(tpl.budget);
    setPrompt(tpl.prompt);
    const start = startDate || getTodayString();
    setStartDate(start);
    setEndDate(addDaysToDate(start, tpl.days - 1));
    setValidationError(null);
    setGenerationError(null);
  };

  const handleGenerate = useCallback(async () => {
    if (!destination.trim()) {
      setValidationError('Destination is required to generate itinerary suggestions.');
      return;
    }

    setValidationError(null);
    setGenerationError(null);
    setIsGenerating(true);
    setGeneratedResult(null);
    setSaveError(null);
    setPartialSaveInfo(null);

    try {
      const res = await fetch('/api/ai/generate-itinerary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          destination: destination.trim(),
          days: Math.max(1, Math.min(10, days)),
          budget: Math.max(0, budget),
          interests: ['culture', 'nature', 'food'],
        }),
      });

      const json = await res.json().catch(() => ({}));

      if (!res.ok) {
        throw new Error(json.error || `Generation failed (${res.status})`);
      }

      if (json.data) {
        setGeneratedResult(json.data);
      } else {
        throw new Error('Received invalid itinerary response from generator');
      }
    } catch (e: any) {
      console.error('Generation failed:', e);
      setGenerationError(e.message || 'Unable to generate itinerary suggestions. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  }, [destination, days, budget]);

  // Auto-generate if prompted from query params on first load
  useEffect(() => {
    const qPrompt = searchParams.get('prompt');
    const qDest = searchParams.get('destination');
    if ((qPrompt || qDest) && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      handleGenerate();
    }
  }, [searchParams, handleGenerate]);

  // Validation before saving
  const validateForSave = (): string | null => {
    if (!title.trim()) {
      return 'Trip title is required.';
    }
    if (!destination.trim()) {
      return 'Destination is required.';
    }
    if (startDate && endDate) {
      const s = new Date(startDate).getTime();
      const e = new Date(endDate).getTime();
      if (!isNaN(s) && !isNaN(e) && e < s) {
        return 'End date must be on or after start date.';
      }
    }
    if (budget < 0) {
      return 'Budget must be a non-negative number.';
    }
    if (!generatedResult) {
      return 'Please generate or review an itinerary draft before saving.';
    }
    return null;
  };

  const handleSaveTrip = async () => {
    const errorMsg = validateForSave();
    if (errorMsg) {
      setValidationError(errorMsg);
      return;
    }

    if (!generatedResult) return;

    setValidationError(null);
    setSaveError(null);
    setPartialSaveInfo(null);
    setIsSaving(true);
    setSaveStatusText('Creating trip record in your workspace...');

    let newTripId: string | null = null;
    const errors: string[] = [];
    let savedStopsCount = 0;
    let savedActivitiesCount = 0;

    const daysList = generatedResult.days || [];
    const totalStopsCount = daysList.length;
    const totalActivitiesCount = daysList.reduce((acc, d) => acc + (d.activities?.length || 0), 0);

    try {
      // 1. Create trip record
      // Destination is preserved in the title and description, as the trips table schema does not have a destination column.
      // cover_image_url is explicitly null to avoid stock or fabricated imagery.
      const tripRes = await fetch('/api/trips', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: title.trim(),
          description: prompt.trim() || `Itinerary focusing on ${destination.trim()}`,
          budget_total: Number(budget) || 0,
          visibility: 'private',
          start_date: startDate || null,
          end_date: endDate || null,
          cover_image_url: null,
        }),
      });

      const tripJson = await tripRes.json().catch(() => ({}));
      if (!tripRes.ok || !tripJson.data?.id) {
        throw new Error(tripJson.error || 'Failed to create trip');
      }

      newTripId = tripJson.data.id;

      // 2. Persist stops and activities
      for (let i = 0; i < daysList.length; i++) {
        const day = daysList[i];
        setSaveStatusText(`Saving stop ${i + 1} of ${daysList.length} (${day.title || `Day ${day.day}`})...`);

        // Compute truthful stop dates if trip start date is provided
        let stopArrivalDate: string | null = null;
        let stopDepartureDate: string | null = null;
        if (startDate) {
          const baseTime = new Date(startDate).getTime();
          if (!isNaN(baseTime)) {
            const dayOffset = (day.day - 1) * 86400000;
            const computedDate = new Date(baseTime + dayOffset).toISOString().split('T')[0];
            stopArrivalDate = computedDate;
            stopDepartureDate = computedDate;
          }
        }

        let stopId: string | null = null;
        try {
          const stopCity = day.city?.trim() || destination.trim();

          const stopRes = await fetch(`/api/trips/${newTripId}/stops`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              city: stopCity,
              country: null,
              arrival_date: stopArrivalDate,
              departure_date: stopDepartureDate,
              order_index: day.day - 1,
            }),
          });

          const stopJson = await stopRes.json().catch(() => ({}));
          if (stopRes.ok && stopJson.data?.id) {
            stopId = stopJson.data.id;
            savedStopsCount++;
          } else {
            errors.push(`Stop for Day ${day.day} (${day.title}): ${stopJson.error || 'Failed to save stop'}`);
          }
        } catch (stopErr: any) {
          errors.push(`Stop for Day ${day.day}: ${stopErr.message || 'Network error'}`);
        }

        // If stop created, save its activities
        if (stopId && day.activities && day.activities.length > 0) {
          for (const act of day.activities) {
            try {
              const actRes = await fetch(`/api/trips/${newTripId}/stops/${stopId}/activities`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  title: act.title,
                  category: ['adventure', 'food', 'nature', 'nightlife', 'culture'].includes(act.category)
                    ? act.category
                    : 'nature',
                  cost: Number(act.estimated_cost) || 0,
                  duration_minutes: Number(act.duration_minutes) || 60,
                  notes: act.notes || null,
                }),
              });

              if (actRes.ok) {
                savedActivitiesCount++;
              } else {
                const actJson = await actRes.json().catch(() => ({}));
                errors.push(`Activity "${act.title}": ${actJson.error || 'Failed to save'}`);
              }
            } catch (actErr: any) {
              errors.push(`Activity "${act.title}": ${actErr.message || 'Network error'}`);
            }
          }
        }
      }

      // Check results
      if (errors.length > 0) {
        // Partial save state: Explain what completed and do NOT silently redirect
        setPartialSaveInfo({
          tripId: newTripId!,
          savedStops: savedStopsCount,
          totalStops: totalStopsCount,
          savedActivities: savedActivitiesCount,
          totalActivities: totalActivitiesCount,
          errors,
        });
      } else {
        // Full success: Navigate to trip itinerary builder
        router.push(`/trips/${newTripId}`);
      }
    } catch (err: any) {
      console.error('Error saving generated trip:', err);
      setSaveError(err.message || 'Failed to save trip. Please try again.');
    } finally {
      setIsSaving(false);
      setSaveStatusText('');
    }
  };

  // Calculate total suggested activity cost
  const totalSuggestedCost = useMemo(() => {
    if (!generatedResult?.days) return 0;
    return generatedResult.days.reduce((sum, d) => {
      return sum + (d.activities?.reduce((actSum, a) => actSum + (Number(a.estimated_cost) || 0), 0) || 0);
    }, 0);
  }, [generatedResult]);

  return (
    <AppShell>
      <div className="max-w-5xl mx-auto space-y-8 pb-16">

        {/* HEADER */}
        <div className="text-center max-w-2xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 text-xs font-semibold mb-3 border border-blue-200 dark:border-blue-800">
            <Sparkles className="w-3.5 h-3.5 text-blue-600 dark:text-blue-400" />
            <span>Itinerary Planning Assistant</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white font-heading tracking-tight">
            Plan Your Trip Itinerary
          </h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-2 leading-relaxed">
            Provide your destination, dates, and budget or start from a sample template. The AI generates draft daily activity suggestions for you to review and customize before saving.
          </p>
        </div>

        {/* PARTIAL SAVE ERROR / NOTIFICATION BANNER */}
        {partialSaveInfo && (
          <div className="p-6 rounded-3xl bg-amber-50 dark:bg-amber-950/40 border border-amber-300 dark:border-amber-800 shadow-sm space-y-4">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-6 h-6 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
              <div>
                <h3 className="text-base font-bold text-amber-900 dark:text-amber-200">
                  Trip Created with Partial Itinerary
                </h3>
                <p className="text-xs text-amber-800 dark:text-amber-300 mt-1 leading-relaxed">
                  Your trip was created, but some generated items could not be saved to the database. Successfully saved{' '}
                  <span className="font-bold">{partialSaveInfo.savedStops}</span> of{' '}
                  <span className="font-bold">{partialSaveInfo.totalStops}</span> stops and{' '}
                  <span className="font-bold">{partialSaveInfo.savedActivities}</span> of{' '}
                  <span className="font-bold">{partialSaveInfo.totalActivities}</span> activities.
                </p>
              </div>
            </div>

            {partialSaveInfo.errors.length > 0 && (
              <div className="bg-white/80 dark:bg-slate-900/80 rounded-2xl p-4 border border-amber-200 dark:border-amber-900/60 max-h-40 overflow-y-auto text-xs space-y-1 font-mono text-amber-900 dark:text-amber-300">
                <div className="font-bold text-[11px] uppercase tracking-wider mb-1 text-slate-500">
                  Failed Items ({partialSaveInfo.errors.length}):
                </div>
                {partialSaveInfo.errors.map((err, idx) => (
                  <div key={idx} className="flex items-start gap-2">
                    <span className="text-amber-600 shrink-0">•</span>
                    <span>{err}</span>
                  </div>
                ))}
              </div>
            )}

            <div className="flex items-center gap-3 pt-2">
              <Link href={`/trips/${partialSaveInfo.tripId}`}>
                <Button className="rounded-xl bg-amber-600 hover:bg-amber-700 text-white font-bold text-xs gap-1.5 shadow-sm">
                  <span>Open Trip in Builder</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Button>
              </Link>
              <Link href="/trips">
                <Button variant="outline" className="rounded-xl text-xs">
                  View All Trips
                </Button>
              </Link>
            </div>
          </div>
        )}

        {/* FULL SAVE ERROR BANNER */}
        {saveError && (
          <div className="p-4 rounded-2xl bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-900/50 flex items-start justify-between gap-3 text-red-800 dark:text-red-300">
            <div className="flex items-start gap-2.5">
              <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400 shrink-0 mt-0.5" />
              <div>
                <h4 className="text-xs font-bold text-red-900 dark:text-red-200">Unable to Save Trip</h4>
                <p className="text-xs text-red-700 dark:text-red-400 mt-0.5">{saveError}</p>
              </div>
            </div>
            <Button
              size="sm"
              onClick={handleSaveTrip}
              className="rounded-full bg-red-600 hover:bg-red-700 text-white text-xs px-3 h-8 shrink-0 flex items-center gap-1.5"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>Retry Save</span>
            </Button>
          </div>
        )}

        {/* VALIDATION ERROR BANNER */}
        {validationError && (
          <div className="p-4 rounded-2xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900/50 flex items-center gap-2.5 text-amber-800 dark:text-amber-300">
            <AlertCircle className="w-5 h-5 text-amber-600 dark:text-amber-400 shrink-0" />
            <p className="text-xs font-semibold">{validationError}</p>
          </div>
        )}

        {/* GENERATOR ERROR BANNER */}
        {generationError && (
          <div className="p-4 rounded-2xl bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-900/50 flex items-start justify-between gap-3 text-red-800 dark:text-red-300">
            <div className="flex items-start gap-2.5">
              <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400 shrink-0 mt-0.5" />
              <div>
                <h4 className="text-xs font-bold text-red-900 dark:text-red-200">Generation Error</h4>
                <p className="text-xs text-red-700 dark:text-red-400 mt-0.5">{generationError}</p>
              </div>
            </div>
            <Button
              size="sm"
              onClick={handleGenerate}
              className="rounded-full bg-red-600 hover:bg-red-700 text-white text-xs px-3 h-8 shrink-0 flex items-center gap-1.5"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>Try Again</span>
            </Button>
          </div>
        )}

        {/* 1. TRIP CONFIGURATION & GENERATOR FORM */}
        <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-xl space-y-6">
          <div className="border-b border-slate-100 dark:border-slate-800 pb-4">
            <h2 className="text-base font-bold text-slate-900 dark:text-white">Trip Details &amp; Parameters</h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Configure your travel details below. All fields can be reviewed and edited prior to saving.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label htmlFor="trip-title" className="text-xs font-bold text-slate-700 dark:text-slate-300 block mb-1.5">
                Trip Title <span className="text-red-500">*</span>
              </label>
              <input
                id="trip-title"
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="e.g., Summer in Kyoto & Osaka"
                className="w-full h-11 px-3.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-sm font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500/30"
              />
            </div>

            <div>
              <label htmlFor="trip-destination" className="text-xs font-bold text-slate-700 dark:text-slate-300 block mb-1.5">
                Destination <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <MapPin className="w-4 h-4 absolute left-3.5 top-3.5 text-slate-400 pointer-events-none" />
                <input
                  id="trip-destination"
                  type="text"
                  value={destination}
                  onChange={(e) => handleDestinationChange(e.target.value)}
                  placeholder="e.g., Tokyo, Japan"
                  className="w-full h-11 pl-10 pr-3.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-sm font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                />
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div>
              <label htmlFor="trip-start-date" className="text-xs font-bold text-slate-700 dark:text-slate-300 block mb-1.5">
                Start Date
              </label>
              <div className="relative">
                <Calendar className="w-4 h-4 absolute left-3.5 top-3.5 text-slate-400 pointer-events-none" />
                <input
                  id="trip-start-date"
                  type="date"
                  value={startDate}
                  onChange={(e) => handleStartDateChange(e.target.value)}
                  className="w-full h-11 pl-10 pr-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500/30 font-mono"
                />
              </div>
            </div>

            <div>
              <label htmlFor="trip-end-date" className="text-xs font-bold text-slate-700 dark:text-slate-300 block mb-1.5">
                End Date
              </label>
              <div className="relative">
                <Calendar className="w-4 h-4 absolute left-3.5 top-3.5 text-slate-400 pointer-events-none" />
                <input
                  id="trip-end-date"
                  type="date"
                  value={endDate}
                  onChange={(e) => handleEndDateChange(e.target.value)}
                  className="w-full h-11 pl-10 pr-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500/30 font-mono"
                />
              </div>
            </div>

            <div>
              <label htmlFor="trip-days" className="text-xs font-bold text-slate-700 dark:text-slate-300 block mb-1.5">
                Duration (Days)
              </label>
              <input
                id="trip-days"
                type="number"
                min={1}
                max={14}
                value={days}
                onChange={(e) => handleDaysChange(Number(e.target.value))}
                className="w-full h-11 px-3.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-sm font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500/30"
              />
            </div>

            <div>
              <label htmlFor="trip-budget" className="text-xs font-bold text-slate-700 dark:text-slate-300 block mb-1.5">
                Total Budget (₹)
              </label>
              <div className="relative">
                <Wallet className="w-4 h-4 absolute left-3.5 top-3.5 text-slate-400 pointer-events-none" />
                <input
                  id="trip-budget"
                  type="number"
                  step={1000}
                  min={0}
                  value={budget}
                  onChange={(e) => setBudget(Math.max(0, Number(e.target.value)))}
                  className="w-full h-11 pl-10 pr-3.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-sm font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                />
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <label htmlFor="trip-prompt" className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Trip Preferences / Prompt (Optional)
            </label>
            <textarea
              id="trip-prompt"
              rows={2}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g., Interested in photography, historic shrines, walking tours, and authentic ramen..."
              className="w-full p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/30 font-medium"
            />
          </div>

          <Button
            onClick={handleGenerate}
            disabled={isGenerating || isSaving}
            className="w-full h-12 rounded-2xl bg-[#2563EB] hover:bg-blue-700 text-white font-bold text-sm shadow-md gap-2"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Generating Itinerary Suggestions...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                <span>Generate Draft Itinerary →</span>
              </>
            )}
          </Button>
        </div>

        {/* 2. CURATED STARTER TEMPLATES */}
        <div>
          <h3 className="font-bold text-base text-slate-900 dark:text-white font-heading mb-3">
            Or Choose a Starter Template
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 mb-4">
            Select a template below to auto-fill sample parameters for your itinerary draft.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {TEMPLATES.map((tpl) => {
              const Icon = tpl.icon;
              return (
                <div
                  key={tpl.id}
                  onClick={() => handleSelectTemplate(tpl)}
                  className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 hover:border-blue-500/40 hover:shadow-lg transition-all cursor-pointer group flex flex-col justify-between"
                >
                  <div>
                    <div className={`w-10 h-10 rounded-xl ${tpl.color} flex items-center justify-center mb-3 group-hover:scale-105 transition-transform`}>
                      <Icon className="w-5 h-5" />
                    </div>
                    <h4 className="font-bold text-sm text-slate-900 dark:text-white font-heading mb-1">{tpl.title}</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">{tpl.desc}</p>
                  </div>
                  <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-[11px] font-semibold text-slate-400">
                    <span>{tpl.days} Days</span>
                    <span className="text-blue-600 dark:text-blue-400">₹{tpl.budget.toLocaleString('en-IN')}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* 3. GENERATED ITINERARY REVIEW CANVAS */}
        {generatedResult && (
          <div className="rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-2xl p-6 sm:p-8 space-y-6 animate-in fade-in-50 duration-500">

            {/* Transparency / Non-reservation Disclaimer Notice */}
            <div className="p-4 rounded-2xl bg-blue-50/70 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-900/60 flex items-start gap-3">
              <Info className="w-5 h-5 text-blue-600 dark:text-blue-400 shrink-0 mt-0.5" />
              <div className="text-xs text-blue-900 dark:text-blue-300 leading-relaxed">
                <span className="font-bold">Draft Planning Suggestions:</span> The suggested stops, activities, estimated costs, and durations below are draft suggestions for planning purposes only. They do not constitute confirmed reservations, bookings, or guaranteed operating hours. Review and adjust all details before saving to your trip workspace.
              </div>
            </div>

            {/* Top Review Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-6 border-b border-slate-100 dark:border-slate-800 gap-4">
              <div>
                <span className="text-xs font-bold text-teal-600 dark:text-teal-400 uppercase tracking-widest flex items-center gap-1.5 mb-1 font-mono">
                  <CheckCircle2 className="w-4 h-4 text-teal-500" />
                  {generatedResult.fallback ? 'Curated Sample Suggestion' : 'AI Suggested Itinerary'}
                </span>
                <h3 className="text-2xl font-extrabold text-slate-900 dark:text-white font-heading">
                  {title}
                </h3>
                <div className="flex items-center gap-3 text-xs text-slate-500 dark:text-slate-400 font-mono mt-1.5 flex-wrap">
                  <span className="flex items-center gap-1">
                    <MapPin className="w-3.5 h-3.5 text-slate-400" />
                    <span>{destination}</span>
                  </span>
                  <span>•</span>
                  <span>{generatedResult.days?.length || days} Days</span>
                  <span>•</span>
                  <span>Estimated Total: ₹{totalSuggestedCost.toLocaleString('en-IN')}</span>
                  <span>•</span>
                  <span>Planned Budget: ₹{budget.toLocaleString('en-IN')}</span>
                </div>
              </div>

              <Button
                onClick={handleSaveTrip}
                disabled={isSaving}
                className="bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold px-6 h-11 shadow-md gap-2 shrink-0 self-start sm:self-auto"
              >
                {isSaving ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    <span>{saveStatusText || 'Saving to Workspace...'}</span>
                  </>
                ) : (
                  <>
                    <span>Save &amp; Open Builder →</span>
                  </>
                )}
              </Button>
            </div>

            {/* Day-by-Day Activities Review */}
            <div className="space-y-4">
              {generatedResult.days?.map((day) => (
                <div
                  key={day.day}
                  className="p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/70 dark:border-slate-700/70 flex flex-col md:flex-row gap-4 justify-between"
                >
                  <div className="md:w-1/3">
                    <span className="text-[11px] font-bold text-blue-600 dark:text-blue-400 uppercase tracking-wider block font-mono">
                      Day {day.day}
                    </span>
                    <h4 className="font-bold text-base text-slate-900 dark:text-white font-heading mt-0.5">
                      {day.title}
                    </h4>
                    {day.city && day.city !== day.title && (
                      <span className="text-xs text-slate-500 dark:text-slate-400 mt-1 block">
                        Location: {day.city}
                      </span>
                    )}
                  </div>

                  <div className="md:w-2/3 space-y-2">
                    {day.activities && day.activities.length > 0 ? (
                      day.activities.map((act, i) => (
                        <div
                          key={i}
                          className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200/60 dark:border-slate-700 flex flex-col gap-1.5"
                        >
                          <div className="flex items-center justify-between gap-2 text-xs">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="w-2 h-2 rounded-full bg-blue-500 shrink-0" />
                              <span className="font-semibold text-slate-800 dark:text-slate-200">{act.title}</span>
                              <span className="px-2 py-0.5 rounded-md bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 font-medium text-[10px] uppercase">
                                {act.category}
                              </span>
                            </div>
                            <span className="font-bold text-slate-700 dark:text-slate-300 font-mono shrink-0">
                              ₹{(Number(act.estimated_cost) || 0).toLocaleString('en-IN')}
                            </span>
                          </div>

                          <div className="flex items-center justify-between gap-2 text-[11px] text-slate-500 dark:text-slate-400 font-mono">
                            <span className="flex items-center gap-1">
                              <Clock className="w-3 h-3 text-slate-400" />
                              <span>{act.duration_minutes || 60} mins</span>
                            </span>
                            {act.notes && (
                              <span className="truncate max-w-[280px] italic text-slate-400 dark:text-slate-500">
                                {act.notes}
                              </span>
                            )}
                          </div>
                        </div>
                      ))
                    ) : (
                      <p className="text-xs text-slate-400 italic">No scheduled activities for this day.</p>
                    )}
                  </div>
                </div>
              ))}
            </div>

            {/* Bottom Save Action Dock */}
            <div className="pt-4 border-t border-slate-100 dark:border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4">
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Saving will create the trip in your private workspace where you can edit, reorder, or delete stops and activities.
              </p>
              <Button
                onClick={handleSaveTrip}
                disabled={isSaving}
                className="bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold px-6 h-11 shadow-md gap-2 shrink-0 w-full sm:w-auto"
              >
                {isSaving ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    <span>{saveStatusText || 'Saving to Workspace...'}</span>
                  </>
                ) : (
                  <>
                    <span>Save &amp; Open Builder →</span>
                  </>
                )}
              </Button>
            </div>

          </div>
        )}

      </div>
    </AppShell>
  );
}

export default function AITripCreatorPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center bg-slate-50 dark:bg-slate-950">
          <div className="w-8 h-8 rounded-full border-2 border-blue-600 border-t-transparent animate-spin" />
        </div>
      }
    >
      <AITripCreatorContent />
    </Suspense>
  );
}
